### ISSUE TITLE
[wish] Collaboration platform

### ISSUE THREAD

**Issue by nicolas-raoul** [Pascalco/harvesttemplates#114]
I love Harvest Templates, and often run jobs. Each job will probably need to be **run again next year**, as new articles appear and more information is added.

PROBLEM: Next year I will probably have switched to another pet project, or have forgotten about these jobs altogether.

QUESTION: Is there a place where people post their Harvest Templates permalinks (or something similar), and the date at which each was last run?

That "place" could even run the jobs automatically once in a while, if that proves safe enough (maybe after review by a few admins?). The advantages would be triple: Not forget running them, not rely on peoples' flimsy web browsers, and generate a success/failure log visible by anyone.

Thanks!

**Comment by Pascalco** [comment]
done: 6ce9905b7f3ea77793c3edcfa0ec61d604ceb32f

**Comment by nicolas-raoul** [comment]
Extremely cool, thanks a lot!
The link for anyone looking for it: https://tools.wmflabs.org/pltools/harvesttemplates/share.php
