### ISSUE TITLE
Parameter not added, for unknown reason

### ISSUE THREAD

**Issue by nicolas-raoul** [Pascalco/harvesttemplates#116]
|画像=[[File:Sakurajima gym.JPG|300px]]

-> no value

| 画像 = [[File:Kokuritsu Kasumigaoka Rikujo Kyogijo-3.jpg|270px]]<br/>新国立競技場 建設状況<br/>（2017年5月6日撮影）

-> added value Kokuritsu Kasumigaoka Rikujo Kyogijo-3.jpg

Why is the first not added?

Permalink: https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=ja&project=wikipedia&namespace=0&property=18&template=%E3%82%B9%E3%82%BF%E3%82%B8%E3%82%A2%E3%83%A0%E6%83%85%E5%A0%B1%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9&parameter=%E7%94%BB%E5%83%8F&category=&depth=0&set=1&offset=0&limit=10000&wikisyntax=0&

**Comment by matejsuchanek** [comment]
It [did happen](https://www.wikidata.org/w/index.php?title=Q11538007&diff=483638824&oldid=252110329).

**Comment by nicolas-raoul** [comment]
@matejsuchanek Thanks for looking into this!
That's very strange, I can swear that Sakurajima item's line turned red in Harvest Templates :-o
