### ISSUE TITLE
do ASK queries instead of loading constraints

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#119]
Wikidata Query Service allows ASK queries, which return boolean values. For example, "Unique value" now uses a (long) array of all present values but instead it could be a simple query like `ASK { ?item wdt:P123 "abcdefg" }`. "Type" or "Value type" are other good candidates.

Not all constraints need this, eg. "Format" or "Conflicts with".

**Comment by Pascalco** [comment]
resolved with a3dc1ef23eabc07fecfe38c1818a3865300f50a6
