### ISSUE TITLE
Request Failed: error, Bad Gateway

### ISSUE THREAD

**Issue by nicolas-raoul** [Pascalco/harvesttemplates#121]
I get this error extremely often, especially if I try to harvest in two tabs at once.

It would be great if that could be fixed.
Either by the tool, or by upstream if it is an upstream problem.

![screenshot from 2017-05-25 15-17-38](https://cloud.githubusercontent.com/assets/99590/26438333/554b69e6-415d-11e7-9d8e-0b8ad925a548.png)

In some cases, the "get pages" button becomes grey. In such cases, clicking the permalink re-opens the page, making the button blue again.

**Comment by Pascalco** [comment]
with 93d9e476fa886707526a4a4e98ae6c6830135f50 this error should now occur less often.
Can you confirm?
