### ISSUE TITLE
Ignore generic image Gthumb.svg

### ISSUE THREAD

**Issue by nicolas-raoul** [Pascalco/harvesttemplates#148]
![240px-gthumb svg](https://user-images.githubusercontent.com/99590/31882501-f7c9a7ec-b821-11e7-90ba-34fc993893ad.png)
https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Gthumb.svg

used for example on:

https://ja.wikipedia.org/wiki/%E6%9D%BE%E5%B0%BE%E6%96%B0%E5%90%BE

**Comment by Pascalco** [comment]
added image to the format constraint of P18: https://www.wikidata.org/w/index.php?title=Property%3AP18&type=revision&diff=584869211&oldid=578860282
