### ISSUE TITLE
[Enhancement] datatype monolingualtext is not yet supported

### ISSUE THREAD

**Issue by nicolas-raoul** [Pascalco/harvesttemplates#150]
I got this message when trying to add birth names (P1477):

https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=ja&project=wikipedia&namespace=0&property=1477&template=Infobox%20%E4%BA%BA%E7%89%A9&parameter=%E5%87%BA%E7%94%9F%E5%90%8D&category=&depth=0&set=1&offset=0&limit=1000000&wikisyntax=0&

That would be great to have this type supported :-)

**Comment by Pascalco** [comment]
duplicate of #131
