### ISSUE TITLE
Result is blank

### ISSUE THREAD

**Issue by mbch331** [Pascalco/harvesttemplates#155]
I tried to import Last FM id from Dutch Wikipedia and I ended up with 0 succesful and 9272 errors
This was the setting: https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=nl&project=wikipedia&namespace=0&property=3192&template=Infobox%20artiest&parameter=lastfm&addprefix=&removeprefix=&category=&depth=0&set=1&offset=0&limit=10000&wikisyntax=0&
There were some constraint violations (22 violations), which are correct, but a lot were blank (579 blanks)
The blanks are strange. I've added the resulting TSV.
[harvesttemplates_P3192_nlwiki.txt](https://github.com/Pascalco/harvesttemplates/files/1649364/harvesttemplates_P3192_nlwiki.txt)

**Comment by Pascalco** [comment]
resolved with 059b363d5dd72d8b330538afbe38415314ed01e5
