### ISSUE TITLE
undefined unit

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#156]
HarvestTemplates sometimes [adds this invalid unit](https://www.wikidata.org/w/index.php?title=Q21905851&action=history). Since `undefined` is a JavaScript keyword, I suspect there's a bug in the interface. Neither me nor the user were able to reproduce this.

**Comment by Pascalco** [comment]
This could have happened if the user pressed "get pages" immediately after typing the property ID and before the unit select menu was loaded.
Loading the unit select menu requires two API calls:
https://github.com/Pascalco/harvesttemplates/blob/b718bbe95d580b93228cd7a39bcd26a6bda55e03/main.js#L1024-L1030 and https://github.com/Pascalco/harvesttemplates/blob/b718bbe95d580b93228cd7a39bcd26a6bda55e03/main.js#L994-L1000
With a slow internet connection, it is possible that one can press "get pages" before these two API calls were executed.

**Comment by Pascalco** [comment]
this got fixed with b1809b4a8711b2c72e50c34fda5c1b22ffbe0d34

**Comment by Pascalco** [comment]
this is still a problem: https://tools.wmflabs.org/editgroups/b/harvesttemplates/18c668858942/

**Comment by Pascalco** [comment]
fixed with 059b363d5dd72d8b330538afbe38415314ed01e5
