### ISSUE TITLE
WQS query expired

### ISSUE THREAD

**Issue by nicolas-raoul** [Pascalco/harvesttemplates#158]
With the query below, pressing on "get pages" always results in "WQS query expired" after a few seconds.

https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=en&project=wikipedia&namespace=0&property=195&template=New%20Testament%20manuscript%20infobox&parameter=now%20at&addprefix=&removeprefix=&category=&depth=0&set=1&offset=0&limit=10000&wikisyntax=0&

Other queries work fine. What is wrong with this query? I believe it is not big.

Strangely:
- If I change the parameter to image it [works](https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=en&project=wikipedia&namespace=0&property=18&template=New%20Testament%20manuscript%20infobox&parameter=image&category=&depth=0&set=1&offset=0&limit=10000&wikisyntax=0&).
- The [underlying SPARQL request](https://query.wikidata.org/bigdata/namespace/wdq/sparql?&query=SELECT+%3Fvalue+WHERE+%7B+VALUES+%3Fcl+%7B+wd%3AQ35120+%7D+.+%3Fvalue+wdt%3AP279*+%3Fcl+%7D&format=json) works from the same browser, resulting in a 2.8 MB JSON file after a minute or so.

**Comment by Pascalco** [comment]
The underlying SPARQL query is on the edge of timing-out. If the query time outs once, the result is cached and then "WQS query expired" pop ups already after a few seconds.
This issue gets solved with #119.

**Comment by Pascalco** [comment]
resolved with a3dc1ef23eabc07fecfe38c1818a3865300f50a6

**Comment by nicolas-raoul** [comment]
Wonderful, thanks :-)
