### ISSUE TITLE
Problems importing Facebook ID

### ISSUE THREAD

**Issue by rdk-pmis** [Pascalco/harvesttemplates#161]
See https://www.wikidata.org/wiki/Topic:Uat2cnssoztr793z there is an issue importing valid Facebook ID's. They are rejected on Format, but are valid according to the property constraints,

**Comment by edgarskos** [comment]
@Pascalco there is [https://github.com/TooTallNate/pcre-to-regexp this thing out there], btw. Not tested it though.

I'm too lazy to do a sparql query right now, but how many properties do we have with non-JS compatible property regexes? If very low number, then maybe we can hardcode them for now? If the library linked above doesn't give any good result

**Comment by Pascalco** [comment]
With new version of the tool, you can disable the format constraint of Facebook ID.
