### ISSUE TITLE
Where is oauth.php

### ISSUE THREAD

**Issue by wetneb** [Pascalco/harvesttemplates#167]
Hi!

I considered contributing one or two pull requests (such as adding a statement and its reference in one edit) but I could not find where the OAuth wrapper `oauth.php` is. It seems to be used by other `pltools` projects. Maybe it would be worth opening this up, or linking to this in the readme if the source is already available online?

Thanks!

**Comment by saerdnaer** [comment]
I had simular problems when I tried to come up with a solution for #40

**Comment by Pascalco** [comment]
The original oauth.php can be found on https://oauth-hello-world.toolforge.org/index.php?action=download.

Current versions of tools don't use anymore oauth.php
