### ISSUE TITLE
Tool Labs page occurred inside the working space

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#17]
![bug](https://cloud.githubusercontent.com/assets/13053169/14151656/376a134a-f6af-11e5-94ad-0d55b700ce30.png)

Happened several times in that run. I'm afraid this could be a security problem.

**Comment by Pascalco** [comment]
Can you reproduce this issue?

**Comment by matejsuchanek** [comment]
No, it has not happened since this report. I will report it whenever it occurs again though. There is coming a maintenance of the servers, so perhaps we can test what the tool will do during it.

**Comment by Pascalco** [comment]
I can now reproduce the problem. When the webservice stops working, the ajax request in the addvalue() function does return a 503 error page. This does not allow to inject foreign code.

**Comment by Pascalco** [comment]
With 795d8fc64be68566c1a4f67d7ae14a85d4aa9b82 HTML tags in the server response are getting escaped.
