### ISSUE TITLE
Avoid P1889 constraint

### ISSUE THREAD

**Issue by bouzinac** [Pascalco/harvesttemplates#173]
Hello, [P1889](https://www.wikidata.org/wiki/Property:P1889#P2302) is a specific property stating that A must be different from B and B different from A.
However, when harvest-templatating {{Distinguish}}, P1889 could not be farmed because of this constraint. Could there be an exception of constraint when farming P1889 ?
![harvest](https://user-images.githubusercontent.com/63542418/79067811-6a787400-7cc2-11ea-9b86-555e92e34d4b.png)

**Comment by Pascalco** [comment]
With the new version of the tool, you can disable non-mandatory constraints.
