### ISSUE TITLE
Links to other namespaces are broken

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#19]
When you work on a set of pages from namespaces requiring prefix (eg. "Category:"), links to these pages don't have this prefix.

![bug1](https://cloud.githubusercontent.com/assets/13053169/14151846/3b59762a-f6b0-11e5-9b5f-c5bae972bfd6.png)

**Comment by Pascalco** [comment]
fixed it for the most common namespaces: ad9f9d7fe22ee51e613773f757ed0f0f88838849
