### ISSUE TITLE
Commons link

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#23]
Commons link constraint for [P935](https://www.wikidata.org/wiki/Property_talk:P935) is not handled correctly because it relies on page existence (so if the input is "Category:Foo" which exists, it goes through even if it is not in the main namespace).

**Comment by Pascalco** [comment]
Is this only a problem for namespace=0 constraints?
So besides checking page existence, one also has to check that no namespace prefix is in the value?

**Comment by matejsuchanek** [comment]
I suggest to check namespace together with whether the page exists, via API. Something like [`action=query&prop=info&indexpageids=`](https://commons.wikimedia.org/w/api.php?action=query&prop=info&titles=Category:Wikipedia&indexpageids=) or so.
