### ISSUE TITLE
Some options are not prefilled correctly

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#26]
`wikisyntax` ("try to match...", uses "wikisyntax" or `undefined` as value) is always unchecked and `set` ("don't load items...", uses 1 or `undefined` as value) is always checked

**Comment by Pascalco** [comment]
`wikisyntax`and `set` now always have value 0 or 1 in the permalink to get prefilled correctly.
Old permalink where `set` was omitted if it was unchecked will still get wrongly prefilled.
