### ISSUE TITLE
[BUG] Extracting parameter from a wrong template

### ISSUE THREAD

**Issue by davidabian** [Pascalco/harvesttemplates#32]
While adding parameter 1 of `:es:Template:NF` as P569, [the tool has extracted the first parameter of a different template, `:es:Template:BDCL`](https://www.wikidata.org/?diff=331856538&oldid=329198640).

It is important to check when this bug has appeared in the past and to revert the affected edits.

See:
* <https://www.wikidata.org/?diff=331856538&oldid=329198640>
* <https://es.wikipedia.org/w/index.php?title=Alfonso_S%C3%A1nchez_Candeira&oldid=90723582&action=edit&section=4>

**Comment by davidabian** [comment]
See also <https://www.wikidata.org/w/index.php?diff=331766421&oldid=331265705>.

**Comment by Pascalco** [comment]
This happended because `:es:Template:BD` is a redirect to `:es:Template:NF`. The parser is then also looking for `:es:Template:BD` and matched unfortunately `:es:Template:BDCL`.
