### ISSUE TITLE
[BUG] constraints violated on P676, Infobox musical and lyrics parameter

### ISSUE THREAD

**Issue by xcombelle** [Pascalco/harvesttemplates#38]
When doing the following request

https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=en&project=wikipedia&namespace=0&property=676&template=Infobox%20musical&parameter=lyrics&category=&depth=0&set=1&

clicking on get values then demo,
there is a lot of results like

Nightingale (musical) → Q960611 → Constraint violation: Type Q2743

According to [[User:Harmonia Amanda]] it's not normal as there is not contrainst violated.

I dig a little in the code and tryed to understand what happen.
My best bet is that the supposely violated constraint is 

Type "musical work (Q2188189)": element must contain property instance of (P31) with classes Q2188189 or their subclasses (defined using subclass of (P279))

because harvesttemplates don't check subclasses.

It's just my best bet. I might be totally wrong

I am not a fluent user of wikidata and I did not code in php since a long time. However ever I can try to make a pull request if you want. I would however prefer that you do the modification yourself if you have time.

**Comment by Pascalco** [comment]
resolved by cf8714b16a332a874c5fb6fe057739e5ac232621 and a90bc8975bce40b75b602638ebd722c042783a1e
