### ISSUE TITLE
load edition ids from the repository

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#4]
Wikidata has [property P1800](https://www.wikidata.org/wiki/Property:P1800) for this.

**Comment by matejsuchanek** [comment]
Alternatively, load from https://www.wikidata.org/wiki/Wikidata:List_of_wikis/python. It's a protected page and enforces correct JSON format.

**Comment by Pascalco** [comment]
resolved with 059b363d5dd72d8b330538afbe38415314ed01e5
