### ISSUE TITLE
Bug with Constraint:Format

### ISSUE THREAD

**Issue by davidabian** [Pascalco/harvesttemplates#49]
This tool seems to compare the text string as is in the source Wikipedia to every {{Constraint:Format}}. Because of that, the text `falta_ imagen_hombre.svg` (check out [here](https://es.wikipedia.org/w/index.php?title=Jerónimo_Gil&oldid=92447457&action=edit)) has not been detected as a constraint violation and has been accepted in the first case, but this file should not be accepted for [P18](https://www.wikidata.org/wiki/Property_talk:P18).

![bug-format-constraint](https://cloud.githubusercontent.com/assets/10131595/17083657/b937edd6-51a7-11e6-925e-3008ba68ad9c.png)

**Comment by mbch331** [comment]
Actually this isn't the fault of Harvesttools. The text it checks against is _falta imagen_ (with 1 space). The found image is _falta__ _imagen_ (2 spaces). That indeed doesn't violate the constraint. Only the display of the name of the image added could be better (it shows only 1 space where there are actually 2), but that's how HTML works. Only when using &lt;pre&gt; &lt;/pre&gt; you get 2 spaces.

**Comment by davidabian** [comment]
I find the bug in checking out the original text, and not the real file name in Commons that will be added to WIkidata.

This file...
https://commons.wikimedia.org/wiki/File:Falta_%20_%20_%20_%20_imagen_hombre.svg
... and this file...
https://commons.wikimedia.org/wiki/File:Falta_________imagen_hombre.svg
... are exactly the same file as...
https://commons.wikimedia.org/wiki/File:Falta_imagen_hombre.svg

In these cases, I think that Harvesttools should consider the file name in Commons, and not the original string, to avoid false positives.

**Comment by mbch331** [comment]
Currently Harvesttools adds the string that is found on the local wiki to Wikidata and doesn't resolve the redirect. If it has to check wether the file is a redirect or a real file, that would slow harvesting down.

**Comment by Pascalco** [comment]
with f171276333323758b913922103f129fb6f3677b5 multiple spaces get now replaced by one space.

**Comment by davidabian** [comment]
Thanks, @mbch331 and @Pascalco!
