### ISSUE TITLE
parameter prefill

### ISSUE THREAD

**Issue by edgarskos** [Pascalco/harvesttemplates#50]
[Link](https://tools.wmflabs.org/pltools/harvesttemplates/?siteid=en&project=wikipedia&namespace=0&property=345&template=IMDb%20title&parameter=id&parameter=1&prefix=tt&category=2016%20films&depth=0&set=1&offset=0&limit=10000&wikisyntax=0&)

Previosly this query prefilled both "Parameter" and "Alias" in form. Now it fills only "Parameter". I assume, [this](https://github.com/Pascalco/harvesttemplates/commit/6fcbbca8401ce5f51f410cd23e75b9799a11669a) one introduced it, so pinging also @matejsuchanek

**Comment by Pascalco** [comment]
fixed by c9dc2c60f5044b7729c8d64a7cf3a23515dc0c3f
