### ISSUE TITLE
Pending load

### ISSUE THREAD

**Issue by edgarskos** [Pascalco/harvesttemplates#59]
About [this one](https://github.com/Pascalco/harvesttemplates/commit/c73bfa39920f7d949ba6bd9282ce0bfe16c8709b), @matejsuchanek . 

Something has gone wrong. "Get pages" is disabled also after pages are loaded.

**Comment by matejsuchanek** [comment]
Noticed, #58

**Comment by edgarskos** [comment]
Yes, I also noticed after pressing save :)
