### ISSUE TITLE
langauge issues

### ISSUE THREAD

**Issue by matejsuchanek** [Pascalco/harvesttemplates#6]
Several times the code is:
```javascript
'https://'+job.lang+'.'+job.project+'.org'
```
which causes the following problems:
1. wikidata.org and mediawiki.org don't have the language part
2. commons/meta/wikispecies have fake langauge part 'commons'/'meta'/'species' which are not language codes
3. we don't care about the language input if language or project input is 'commons', 'mediawiki', 'wikidata', however we still save it in 
```javascript
lang: $('input[name="lang"]').val(),
```
and then call in
```javascript
$.each ( ( monthnames[job.lang]||{} ) , function ( name , num ) {
```

(Meta and mediawiki.org are not supported yet.)

**Comment by Pascalco** [comment]
resolved 1b774241b066c5134c2a1daa384c0003a81f217b
