### ISSUE TITLE
Template redirects

### ISSUE THREAD

**Issue by edgarskos** [Pascalco/harvesttemplates#76]
About #73, @matejsuchanek.

Hasn't the template redirects been hidden with it? Can't give example query, but HT gave "Template not found", if article has template redirect (not in reference, of course). Or maybe that was temporary issue.

**Comment by matejsuchanek** [comment]
I made a typo in `preg_quote` which was fixed in ad96087.

**Comment by edgarskos** [comment]
OK, thanks.
