### ISSUE TITLE
support {{URL|}} form of website parameter

### ISSUE THREAD

**Issue by dachary** [Pascalco/harvesttemplates#91]
In https://en.wikipedia.org/wiki/BIDS_Helper the website parameter of the software infobox has 
<pre>
|website                = {{URL|orienteering.sourceforge.net/drosera}}
</pre>
which is not a supported value for the [official website](https://www.wikidata.org/wiki/Property:P856) property. It should be converted into something shorter, possibly with a regexp.

**Comment by Pascalco** [comment]
duplicate of #2
