### ISSUE TITLE
can't parse templates with regex characters

### ISSUE THREAD

**Issue by Pascalco** [Pascalco/harvesttemplates#92]
reported at https://www.wikidata.org/wiki/Topic:Tbzuoq2wi6lnma9d and https://www.wikidata.org/wiki/Topic:Takgkov3tj11exrl

@matejsuchanek: The problem is most likely caused by the escape of regex character at https://github.com/Pascalco/harvesttemplates/blob/db8a9c99b987b773474a947d1fe050ae4f059298/main.js#L743 but I'm unsure if removing it causes other problems.

**Comment by matejsuchanek** [comment]
made PR #93, introduced by me in 215842eecc97f3c6bdbae3c2e19f4f102494b702 as `escape template name in one more case`
